### ISSUE TITLE
请问后台服务的目录和文件需要设置哪些权限?

### ISSUE THREAD

**Issue by ikokang** [alanhi/WifiDogService-PHP#1]
今天刚下载你的认证服务程序，不知道哪些目录和文件是否需要设置权限？

**Comment by alanhi** [comment]
我这边把代码放入php服务器运行就行了，本地mysql数据库
CREATE TABLE `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(16) DEFAULT NULL,
  `password` varchar(16) DEFAULT NULL,
  `token` varchar(40) DEFAULT NULL,
  `logintime` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
